[tool.pylint.master]
init-hook = 'import sys; sys.path.insert(0, ".")'

[tool.pylint.messages_control]
disable = "missing-docstring"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.design]
max-args = 10
max-locals = 20
max-branches = 15
max-statements = 60
